- hosts: localhost
  gather_facts: False
  tasks:
    - name: Create a key pair and return the private key
      amazon.aws.ec2_key:
        name: demokey
        region: us-east-1
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
      register: keyout
      
    - name: Save private key to file
      ansible.builtin.copy:
        content: "{{ keyout.key.private_key }}"
        dest: ./demokey.pem
      when: keyout.changed == True # save private key if key doesn't exist yet

    - name: Create an EC2 instance, use created key
      amazon.aws.ec2_instance:
        name: "ansible"
        key_name: "demokey"
        instance_type: t2.micro
        exact_count: 1
        security_group: default
        aws_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_access_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        region: us-east-1
        # network_interfaces:
        #  - assign_public_ip: true
        image_id: ami-0e0416d387552f0b1
        tags:
          Environment: Testing
      register: ec2_output

    - name: Print public IP of created EC2 instance
      debug:
        var: ec2_output.instances[0].network_interfaces[0].association.public_ip