---
- name: Web Server Setup
  hosts: webservers
  become: true # execute all tasks with sudo
  tasks:
    - name: Install httpd
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Start and enable httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes